### ISSUE TITLE
Inconsistency between qhub.readthedocs.io and qhub.dev

### ISSUE THREAD

**Issue by filippo82** [Quansight/qhub-cloud#145]
Hi all,

I wanted to make you aware that  https://qhub.readthedocs.io/ and https://qhub.dev are **not** showing the same content (I believe that https://qhub.dev is the updated one).

Is this expected?

Best,
-Filippo

**Comment by filippo82** [comment]
They are still **NOT** showing the same content ... Could you please remove one of the two?

**Comment by laisbsc** [comment]
As of now (Dec 2020), we have QHub's launch at JupyterCon with the [readthedocs](https://qhub.readthedocs.io/) URL (which returns a 404) and the [qhub.dev](https://qhub.dev) with the actual documentation.

Solutions are either:
- Point both URL addresses to the same docs (files); OR
- Keep only one URL (since the readthedocs is on the video, this is the chosen one).

**Comment by laisbsc** [comment]
After a long discussion, we've decided that the https://qhub.readthedocs.io/ will no longer point to QHub's documentation.

As of now, we have the `dev` branch deploying the docs at [cloud.qhub.dev/latest](https://cloud.qhub.dev/en/latest/) and the `main` branch deploying to [cloud.qhub.dev/stable](https://cloud.qhub.dev/en/stable/).

As a medium-term plan, we will have the web address [qhub.dev](qhub.dev/) to host a webpage for QHub, exemplifying the tool and showcasing usability, etc. similar to [Dask](https://dask.org/). That page will have a link on the Nav bar to direct the user to the docs, which will be continued to be hosted using the ReadTheDocs but not the same URI.

We truly appreciate your report @filippo82. I will go ahead and close this for now since we have sorted the double URL confusion.
Thanks a million and if you get a chance, let us know what you think of the new docs. :)
