### ISSUE TITLE
Update the PyPI qhub package

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub-cloud#164]
I tried deploying qhub this weekend.  The instructions listed https://qhub.readthedocs.io/en/latest/docs/step-by-step-walkthrough.html will fail using qhub installed via `pip`.  Using the version of qhub in the current repo allowed me to finish deployment.

**Comment by prasunanand** [comment]
Seems like a documentation issue to me.

**Comment by laisbsc** [comment]
I think this might have been sorted since there were so many people installing QHub since this was opened.

I will go ahead and close this since I think It has gotten stale (and loss it's relevance). Hopefully we nailed the installation docs, will know more after the user comes back with the feedback :)
