### ISSUE TITLE
[bug] Unreliable /shared disk behavior on AWS

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub-cloud#304]
## Describe the bug
I'm getting unreliable behavior with the Qhub users filesystem (e.g. /shared/data) on AWS. 

I downloaded some netcdf files, and when reading the files in my workflow, I'm getting errors randomly.

Sometimes the workflow works, and sometimes it errors out on one of the files with this error: `OSError: [Errno -101] NetCDF: HDF error: b'/home/shared/users/rsignell/data/NWM/1993/1993022313.LAKEOUT_DOMAIN1.comp`.  

It's not always the same file, of course.   So sometimes it works, and sometimes it fails with that error on a random file.

**Comment by tylerpotts** [comment]
@rsignell-usgs I don't think this is a bug. I think this is a side effect of the very slow speed of the `/home/shared` nfs mounted volume. It's gotten as slow as 600KB/s in my experience. It's designed as a way to share code for quick collaboration. 

For any sort of computational task, I highly recommend storing your data in an S3 type block storage and reading it in with Dask. Ideally creating the dask task graph locally, and then with a cluster spun up running the `.compute()` so that the workers in the cluster each will read a subset of the tasks in parallel from S3.

Funny enough, I happened to draft a diagram recently to explain the flow of data to a colleague. I'll attach it below in case it's useful.

![QHub Cloud Data Flow Diagram for Computational Tasks](https://user-images.githubusercontent.com/49161327/106933409-7a909280-66de-11eb-85fa-19d399328e04.png)

**Comment by rsignell-usgs** [comment]
Ooh, "terrible, leads to errors".   Yep, that's it!!!

@tylerpotts,  yes normally I would use object storage, but reading NetCDF (at least using the NetCDF/HDF5 libraries) doesn't perform well, so for this "conversion-of-1000s-of-NetCDF-files workflow", we usually use fast local disk.   But of course this isn't fast local disk.
