### ISSUE TITLE
Create issue on jupyterhub/jupyterhub about extension mechanism for jupyterhub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#395]

**Comment by costrouc** [comment]
Scratch pad

**Comment by costrouc** [comment]
# JupyterHub Extension Mechanism

This is a proposal to start the discussion on an extension mechanism for JupyterHub. For myself this is motivated by the work that we have been doing at Quansight to extend JupyterHub in [qhub-cloud](https://github.com/quansight/qhub-cloud) and [qhub-onprem](https://github.com/quansight/qhub-onprem). I think of extensions as extending Jupyterhub in ways that the JupyterHub core might not want to adopt while allowing tighter integration with the JupyterHub internals.

The current direction I see users being steered into for extending JupyterHub is via services. This is a great fit for many use cases. These services are exposed under `/services/<service-name>` and depending on the token access have full access to the JupyterHub REST API. Additionally a tab in JupyterHub menu exposes the services to a logged in user.

When I think of extending JupyterHub I think of the following:

1.  how to add additional REST routes? `c.JupyterHub.extra_handlers` also handled by services currently
2.  how to modify hub templates? `c.JupyterHub.template_paths`
3.  how to modify and read properties not exposed via the REST API?
4.  how to add additional database tables to JupyterHub?
5.  how to add hooks to the spawner actions?

Issues 1-4 have come up when we are trying to extend JupyterHub.

## Theming

Why is there not an easy way to theme JupyterHub? The [current docs](https://jupyterhub.readthedocs.io/en/stable/reference/templates.html) show the user how to modify (2) `c.JupyterHub.template_paths` and `c.JupyterHub.template_vars`. But what is users have static files they need to serve as well? Then they also need to modify (1) `c.JupyterHub.extra_handlers`.

We have a package [Quansight/qhub-jupyterhub-theme](https://github.com/quansight/qhub-jupyterhub-theme) that tries to expose common theming options that users may want e.g. logo, colors, and text. But we have to resort to the instructions of

```python
c.JupyterHub.extra_handlers = [
    (r'/custom/(.*)', tornado.web.StaticFileHandler, {"path": qhub_jupyterhub_theme.STATIC_PATH}),
]

c.JupyterHub.template_paths = [
    qhub_jupyterhub_theme.TEMPLATE_PATH
]
```

What happens if the handles and template paths have already been set?
What happens if there is already a `/custom/*` route defined?

## [ideonate/cdsdashboards](https://github.com/ideonate/cdsdashboards)

Dashboarding is a common need of clients we have worked with. Often times they would like to develop a dashboard within a notebook and then "share" it with others. cdsdashboards extends JupyterHub (in some undocumented ways) to extend JupyterHub and was the main motivation for this proposal.

CDS Dashboards does several things in extending JupyterHub:

-   (1) adds dashboard api routes via `c.JupyterHub.extra_handlers`
-   (2) adds dashboard routes via `c.JupyterHub.template_paths`
-   (3/4) adds dashboard database table for keeping track of dashboards and users with permissions

## [yuvipanda/jupyterhub-ssh](https://github.com/yuvipanda/jupyterhub-ssh)

Yuvi wrote a brilliant tool jupyterhub-ssh that allows users to "ssh" into their jupyterlab terminals. This work originated from his earlier work [yuvipanda/kubessh](https://github.com/yuvipanda/kubessh). This tool does not require jupyterhub permissions and users the users apikey as a password to launch terminal sessions. We opened a [feature request](https://github.com/yuvipanda/jupyterhub-ssh/issues/25) where we would like to store ssh public keys for a given user in jupyterhub. These ssh-keys
should be "public" information. Much like github shows all user's github public keys `github.com/<username>.keys`. The problem is that jupyterhub currently has auth<sub>state</sub> which is really for private
information and is not accessible to the user via the api.

Thus we think that a user/group management console would be appropriate here to associate secrets, public information to each
user/group. Additionally this management console could allow secrets to be auto created as environment variables when a jupyterlab server is spawned. This would require:

-   (1) add api routes for user/group secrets and public `c.JupyterHub.extra_handlers`
-   (2) add api template routes for displaying user management
-   (3/4) database table for storing secrets (encrypted), public information
-   (5) spawner start hooks to add environment secrets to jupyterlab launched session

This is not a proposal to implement user/group management (which we would like to do) but to show extensions that definitely do not fit in jupyterhub core but could be extremely useful to users and not able to be done by jupyterhub services.

## (future extension) Accounting

When we work with clients we get this question very often. How do I manage the resources that a user have access to? How do I restrict users to `X` cpu-hours of compute. This would require:

-   (1) add api routes for user/group accounting
-   (2) add api template routes for displaying user accounting
-   (3/4) database table for storing cpus-usage etc.
-   (5) spawner start/poll/stop hooks to monitor resource usage

Again this is not a proposal to implement jupyterhub accounting but that services do not currently ratify the needs of these extensions.

# Proposal

**Comment by danlester** [comment]
I think adding to extra_handlers and template_paths is trivial really, certainly when the admin already has to choose things like the VariableKubeSpawner elsewhere in jupyterhub_config.py. But one solution is to write our own helper routines to add items to the config:

```
from cdsdashboards.hubextension import config_for_dashboards

config_for_dashboards(c)
```

This is an alternative way to add template_paths and extra_handlers. Code is [here](https://github.com/ideonate/cdsdashboards/blob/86d0fdce80df614c12f9332eb09bfdeca9d2a543/cdsdashboards/hubextension/__init__.py#L43) (and could do a lot more).

But I don't advertise that because the admin already has to do so much config editing, and I think it's easier for them to understand what's going on, especially if they also have other custom templates that they need to merge. The qhub-jupyterhub-theme module could simplify the copy-and-paste by exposing its own 'extra_handler' as it does for the template_path (and as cdsdashboards does).

The issues that really prevent two extensions like ContainDS Dashboards being able to run simultaneously using the undocumented hooks are:

- How to merge templates themselves - e.g cdsdashboards does stuff to the list of servers in home.html; what if the other extension wants to do different things.
- Database extensions via ORM. The way cdsdashboards extends the database (adding Dashboard class and also adding a relationship between Dashboard and Server) depends entirely on the fact that JupyterHub's ORM is imported for the first time in each JH run by cdsdashboards itself which can then immediately extend it before sqlalchemy settles on the ORM classes. If JH decided to interact with its ORM before processing jupyterhub_config.py (which in turn imports cdsdashboards, which imports JH's ORM) then this would break.

It may be that cdsdashboards should find other ways to do this. Instead of maintaining a relationship between Dashboard and Server ORM models (which is very helpful because deleting one deletes the other), it should perhaps be forced to maintain its own separate list of 'Dashboard' Servers, and then 'Server delete' hooks might be fired within cdsdashboards by JH when a Server is deleted, and cdsdashboards has to go and see if that affects its Dashboards.

Likewise, maybe it shouldn't be allowed to change home.html directly. Or changes should be made via Javascript, where JupyterLab provides inspiration that having everything extendable and replaceable doesn't lead to many conflicts between extensions (as far as I'm aware).

**Comment by costrouc** [comment]
Opened issue here https://github.com/jupyterhub/jupyterhub/issues/3416
