### ISSUE TITLE
Storing example-user initial password somehow

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#445]
Right now `qhub init ...` will generate a random password for the user.

See https://github.com/Quansight/qhub-cloud/runs/2218787116?check_suite_focus=true#step:13:9 and it makes it hard for automation and for the user to later reference if they forget to copy the password down. 

Write down the password locally in `QHUB_DEFAULT_PASSWORD`.

**Comment by danlester** [comment]
Just trying to work with this in some Cypress tests - default password being written to a file named QHUB_DEFAULT_PASSWORD.

The problem is that it's saved in a randomly-named temp file... if I need to remember that location, I might as well just remember the password :)

Maybe I've missed something, and there certainly are drawbacks with alternative locations:

- If in the same folder as qhub-config.yaml, you will want to add the filename to .gitignore, but maybe that's not safe enough to risk.
- If in ~/QHUB_DEFAULT_PASSWORD, that's probably safer in terms of accidental exposure, but it's also likely to stay there forever!

If the main aim is to be able to obtain the password in code, Python should be able to do this as long as it's not too much later:

```
import tempfile, os
print(os.path.join(tempfile.gettempdir(), 'QHUB_DEFAULT_PASSWORD'))
```

But I'm not sure how or when the temp folder location can change.
